language: java
jdk:
  - oraclejdk8
env:
  global:
    - secure: "idDQHs5MtIPAKhU6LzPy4pwCGuxQ8H6/X2nK5L+j6USzrsMGX2lpTBI+r06HGtegGlvtIGY4sZq14pBRd1xAw1bzMw8VOI6JvyEy27kvujSow6xBy+Obv+1pO3rnIGgNQPWaHBs8zJXNI/JnzAMjFtwr0Aics0bSwayqkhoa1wY="
after_success:
  - ./deploy.sh