language: java
jdk:
  - oraclejdk8
env:
  global:
    - secure: "Gj8zkuyn9RnuMWlSXR3hlSGG95kbgK4DWEFMNV2kAahlW8LnIHMK0cAo56i6R3eGI3+gwkZLHl4Hqsdphsgwm37DKeI/ij5Z/mrNPy+Cg0BxYy8FLJNrpcpuuVVHjLjX+YrpxPgNTSAZLAeE/6iE/ffpj+e1iP04iXev9EFXQZM="
before_install:
  - git clone git://github.com/rocketscience-projects/rocket-base.git ../rocket-base
after_success:
  - ../rocket-base/deploy.sh
